# encryption-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-encryption-deployment
  namespace: {{ include "encryption.namespace" . }}
  labels:
    app: encryption
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: encryption
  template:
    metadata:
      labels:
        app: encryption
    spec:
      containers:
        - name: encryption-service
          image: {{ .Values.encryptionService.image }}:{{ .Values.encryptionService.tag }}
          ports:
            - containerPort: {{ .Values.encryptionService.service.port }}
          imagePullPolicy: Always
          resources:  
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.encryptionService.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.encryptionService.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            runAsUser: 1000
