{{- range $key, $service := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  namespace: {{ include "miraculin.namespace" $ }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      containers:
        - name: {{ $service.name }}
          image: {{ $.Values.repo }}-{{ $key }}:{{ $service.version }}
          ports:
            - containerPort: {{ $service.targetPort }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: {{ $service.resources.requests.cpu }}
              memory: {{ $service.resources.requests.memory }}
            limits:
              cpu: {{ $service.resources.limits.cpu }}
              memory: {{ $service.resources.limits.memory }}
{{- $envVars := include "miraculin.envVars" $ | trim }}
{{- $storageSecrets := include "miraculin.storageSecrets" $ | trim }}
{{- $envDependencies := include "miraculin.envDependencies" $service | trim }}
{{- if or $envVars $storageSecrets $envDependencies }}
          env:
{{- if eq $key "storage" }}
{{ $storageSecrets | indent 12 }}
{{ $envVars | indent 12 }}
{{ $envDependencies | indent 12 }}
{{- else }}
{{ $envVars | indent 12 }}
{{ $envDependencies | indent 12 }}
{{- end }}
{{- end }}
---
{{- end }}
