{{- range $key, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ include "miraculin.namespace" $ }}
spec:
  selector:
    app: {{ $service.name }}
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.targetPort }}
      {{- if eq $service.type "LoadBalancer" }}
      nodePort: {{ include "miraculin.nodePort" $ }}
      {{- end }}
  type: {{ $service.type }}
---
{{- end }}
