{{- range $key, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}-service
  namespace: {{ include "miraculin.namespace" $ }}
spec:
  selector:
    app: {{ $svc.name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.targetPort }}
  {{- if eq $svc.type "LoadBalancer" }}
      nodePort: {{ ternary $svc.nodePort.prod $svc.nodePort.test $.Values.setEnvVar.prod }}
  {{- end }}
  type: {{ $svc.type }}
{{- end }}
