# web-interface-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-interface-deployment
  namespace: {{ include "web.namespace" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-interface
  template:
    metadata:
      labels:
        app: web-interface
    spec:
      containers:
        - name: web-interface-service
          image: {{ .Values.webService.image }}:{{ .Values.webService.tag }}
          ports:
            - containerPort: {{ .Values.webService.service.port }}
          imagePullPolicy: Always
          env:
            - name: ENCRYPTION_SERVICE_URL
              value: {{ .Values.encryptionServiceURL}}
            - name: STORAGE_SERVICE_URL
              value: {{ .Values.encryptionServiceURL }}
          resources:  
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:  
            httpGet:
              path: /healthz  
              port: {{ .Values.webService.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:  
            httpGet:
              path: /ready  
              port: {{ .Values.webService.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:  
            runAsUser: 1000
