# storage-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
  namespace: miraculin-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      containers:
        - name: storage-service
          image: badafald/miraculin-storage:v0.2.3
          ports:
            - containerPort: 5002
          imagePullPolicy: Always
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_password
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
          resources:  
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /healthz  
              port: 5002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready  
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
