# web-interface-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-interface-service
  namespace: test-miraculin-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-interface-service
  template:
    metadata:
      labels:
        app: web-interface-service
    spec:
      containers:
        - name: web-interface-service
          image: badafald/miraculin-web:v0.2.3
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          env:
            - name: ENCRYPTION_SERVICE_URL
              value: http://encryption-service:5001
            - name: STORAGE_SERVICE_URL
              value: http://storage-service:5002
          resources:  
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:  
            httpGet:
              path: /healthz  
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:  
            httpGet:
              path: /ready  
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:  
            runAsUser: 1000
