apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: encryption-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Badafald/miraculin.git'
    targetRevision: HEAD
    path: 'k8s/encryption_service'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-miraculin-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
