apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Badafald/miraculin.git'
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values-storage.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-miraculin-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
