# only 1 environment can be specified for deployment
# use (true/false) or (false/true) only, made for security considerations

setEnvVar:
  test: true
  # Only one of these two can be true
  prod: false

repo: badafald/miraculin

services:
  encrypt:
    name: encrypt
    version: v0.2.3
    targetPort: 5001
    port: 5001
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
